# Generated by Django 5.2.5 on 2025-11-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustomword',
            options={'verbose_name': 'CUSTOM_VOCABULARY', 'verbose_name_plural': 'CUSTOM_VOCABULARY'},
        ),
        migrations.AlterModelOptions(
            name='userwordsprogress',
            options={'verbose_name': 'BASIC_EN: Статус слова', 'verbose_name_plural': 'BASIC_EN: Статуси слів'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'BASIC_EN: Слово', 'verbose_name_plural': 'BASIC_EN: Слова'},
        ),
        migrations.RemoveField(
            model_name='word',
            name='is_irregular_verb',
        ),
        migrations.RemoveField(
            model_name='word',
            name='is_modal_verb',
        ),
        migrations.RemoveField(
            model_name='worddeutch',
            name='is_modal_verb',
        ),
        migrations.RemoveField(
            model_name='worddeutch',
            name='is_trennbar_verb',
        ),
        migrations.RemoveField(
            model_name='worddeutch',
            name='is_vokalwechsel_verb',
        ),
    ]
