# Generated by Django 5.2.5 on 2025-09-14 08:14

import django.db.models.deletion
import mysite.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_level', models.CharField(default='', max_length=2)),
                ('word_type', models.CharField(default='', max_length=20)),
                ('article', models.CharField(default='', max_length=4)),
                ('word', models.CharField(max_length=30)),
                ('transcription', models.CharField(default='', max_length=30)),
                ('translation', models.CharField(default='', max_length=30)),
                ('translation_options', models.TextField(default='')),
                ('synonims', models.TextField(default='NO SYNONIM FOR THIS WORD')),
                ('comment', models.TextField(default='')),
                ('is_irregular_verb', models.BooleanField(default=True)),
                ('is_modal_verb', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ENGLISH: Слово',
                'verbose_name_plural': 'ENGLISH: Слова',
            },
        ),
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='БЕЗ КАТЕГОРІЇ', max_length=255, unique=True, verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('current_exp', models.IntegerField(default=0)),
                ('currency', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionaries', models.JSONField(default=mysite.models.set_default_dictionaries_settings)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Налаштування користувача',
                'verbose_name_plural': 'Налаштування користувача',
            },
        ),
        migrations.CreateModel(
            name='UserWordsProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PROCESS', 'In Process'), ('BOX_1', 'Box 1'), ('BOX_2', 'Box 2'), ('BOX_3', 'Box 3'), ('LEARNT', 'Learnt'), ('REPEAT', 'Repeat')], default='NEW', max_length=10)),
                ('repetition_count', models.IntegerField(default=0)),
                ('status_changed_date', models.DateTimeField(auto_now=True)),
                ('was_learnt_once', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.word')),
            ],
            options={
                'verbose_name': 'ENGLISH: Статус слова',
                'verbose_name_plural': 'ENGLISH: Статуси слів',
            },
        ),
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.ForeignKey(default=mysite.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.wordcategory'),
        ),
        migrations.CreateModel(
            name='WordDeutch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word_level', models.CharField(default='', max_length=2)),
                ('word_type', models.CharField(default='', max_length=20)),
                ('article', models.CharField(default='', max_length=4)),
                ('word', models.CharField(max_length=30)),
                ('transcription', models.CharField(default='', max_length=30)),
                ('translation', models.CharField(default='', max_length=30)),
                ('translation_options', models.TextField(default='')),
                ('synonims', models.TextField(default='NO SYNONIM FOR THIS WORD')),
                ('comment', models.TextField(default='')),
                ('is_irregular_verb', models.BooleanField(default=True)),
                ('is_modal_verb', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=mysite.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.wordcategory')),
            ],
            options={
                'verbose_name': 'DEUTCH: Слово',
                'verbose_name_plural': 'DEUTCH: Слова',
            },
        ),
        migrations.CreateModel(
            name='UserWordsDeutchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PROCESS', 'In Process'), ('BOX_1', 'Box 1'), ('BOX_2', 'Box 2'), ('BOX_3', 'Box 3'), ('LEARNT', 'Learnt'), ('REPEAT', 'Repeat')], default='NEW', max_length=10)),
                ('repetition_count', models.IntegerField(default=0)),
                ('status_changed_date', models.DateTimeField(auto_now=True)),
                ('was_learnt_once', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.worddeutch')),
            ],
            options={
                'verbose_name': 'DEUTCH: Статус слова',
                'verbose_name_plural': 'DEUTCH: Статуси слів',
            },
        ),
        migrations.CreateModel(
            name='WordSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Підкатегорія')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='mysite.wordcategory')),
            ],
            options={
                'verbose_name': 'Підкатегорія',
                'verbose_name_plural': 'Підкатегорії',
            },
        ),
        migrations.AddField(
            model_name='worddeutch',
            name='sub_category',
            field=models.ForeignKey(default=mysite.models.get_default_subcategory, on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.wordsubcategory', verbose_name='Підкатегорія'),
        ),
        migrations.AddField(
            model_name='word',
            name='sub_category',
            field=models.ForeignKey(default=mysite.models.get_default_subcategory, on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.wordsubcategory', verbose_name='Підкатегорія'),
        ),
        migrations.CreateModel(
            name='UserCustomWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('word_level', models.CharField(default='', max_length=2)),
                ('word_type', models.CharField(default='', max_length=20)),
                ('article', models.CharField(default='', max_length=4)),
                ('word', models.CharField(max_length=30)),
                ('transcription', models.CharField(default='', max_length=30)),
                ('translation', models.CharField(default='', max_length=30)),
                ('translation_options', models.TextField(default='')),
                ('synonims', models.TextField(default='NO SYNONIM FOR THIS WORD')),
                ('comment', models.TextField(default='')),
                ('is_irregular_verb', models.BooleanField(default=True)),
                ('is_modal_verb', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REPEAT', 'Repeat'), ('BOX_1', 'Box 1'), ('BOX_2', 'Box 2'), ('BOX_3', 'Box 3'), ('LEARNED', 'Learned')], default='NEW', max_length=20)),
                ('status_changed_date', models.DateTimeField(auto_now=True)),
                ('repetition_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_words', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=mysite.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.wordcategory')),
                ('sub_category', models.ForeignKey(default=mysite.models.get_default_subcategory, on_delete=django.db.models.deletion.SET_DEFAULT, to='mysite.wordsubcategory', verbose_name='Підкатегорія')),
            ],
        ),
    ]
