# Generated by Django 5.2.3 on 2025-07-26 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word_level', models.CharField(default='', max_length=2)),
                ('word_type', models.CharField(default='', max_length=20)),
                ('article', models.CharField(default='', max_length=4)),
                ('eng', models.CharField(max_length=30)),
                ('transcription', models.CharField(default='', max_length=30)),
                ('forms', models.CharField(default='', max_length=40)),
                ('ukr', models.CharField(default='', max_length=30)),
                ('commentary', models.TextField(default='')),
                ('synonims', models.TextField(default='')),
                ('category', models.CharField(default='', max_length=20)),
                ('sub_category', models.CharField(default='', max_length=20)),
                ('is_oxford', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='UserWordsProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PROCESS', 'In Process'), ('BOX_1', 'Box 1'), ('BOX_2', 'Box 2'), ('BOX_3', 'Box 3'), ('LEARNT', 'Learnt'), ('REPEAT', 'Repeat')], default='NEW', max_length=10)),
                ('repetition_count', models.IntegerField(default=0)),
                ('status_changed_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.word')),
            ],
            options={
                'verbose_name': 'Статус слова',
                'verbose_name_plural': 'Статуси слів',
            },
        ),
    ]
