# Generated by Django 5.2.3 on 2025-08-22 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word_level', models.CharField(default='', max_length=2)),
                ('word_type', models.CharField(default='', max_length=20)),
                ('article', models.CharField(default='', max_length=4)),
                ('eng', models.CharField(max_length=30)),
                ('transcription', models.CharField(default='', max_length=30)),
                ('ukr', models.CharField(default='', max_length=30)),
                ('translation_options', models.TextField(default='')),
                ('synonims', models.TextField(default='NO SYNONIM FOR THIS WORD')),
                ('comment', models.TextField(default='')),
                ('category', models.CharField(default='', max_length=20)),
                ('sub_category', models.CharField(default='', max_length=20)),
                ('is_irregular_verb', models.BooleanField(default=True)),
                ('is_modal_verb', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('current_exp', models.IntegerField(default=0)),
                ('currency', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_words_number', models.PositiveIntegerField(default=15)),
                ('new_words_number', models.PositiveIntegerField(default=5)),
                ('min_words_number', models.PositiveIntegerField(default=20)),
                ('box_1_limit', models.PositiveIntegerField(default=90)),
                ('box_2_limit', models.PositiveIntegerField(default=150)),
                ('box_3_limit', models.PositiveIntegerField(default=150)),
                ('testing_days_limit', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Налаштування користувача',
                'verbose_name_plural': 'Налаштування користувача',
            },
        ),
        migrations.CreateModel(
            name='UserWordsProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PROCESS', 'In Process'), ('BOX_1', 'Box 1'), ('BOX_2', 'Box 2'), ('BOX_3', 'Box 3'), ('LEARNT', 'Learnt'), ('REPEAT', 'Repeat')], default='NEW', max_length=10)),
                ('repetition_count', models.IntegerField(default=0)),
                ('status_changed_date', models.DateTimeField(auto_now=True)),
                ('was_learnt_once', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.word')),
            ],
            options={
                'verbose_name': 'Статус слова',
                'verbose_name_plural': 'Статуси слів',
            },
        ),
    ]
