# Generated by Django 5.2.5 on 2025-09-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsubcategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
