# Generated by Django 5.2.3 on 2025-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='synonims',
            field=models.TextField(default='NO SYNONIM FOR THIS WORD'),
        ),
    ]
