# Generated by Django 5.2.3 on 2025-08-15 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_word_synonims'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_words_number', models.PositiveIntegerField(default=15)),
                ('new_words_number', models.PositiveIntegerField(default=5)),
                ('min_words_number', models.PositiveIntegerField(default=20)),
                ('daily_reps', models.PositiveIntegerField(default=20)),
                ('new_words_per_day', models.PositiveIntegerField(default=5)),
                ('dark_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
