# Generated by Django 5.2.5 on 2025-10-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_wordsubcategory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='max_endurance',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='max_hitpoints',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='max_mana',
            field=models.IntegerField(default=10),
        ),
    ]
