# Generated by Django 5.2.3 on 2025-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='daily_reps',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='new_words_per_day',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='box_1_limit',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='box_2_limit',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='box_3_limit',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='testing_days_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
