# Generated by Django 5.2.3 on 2025-08-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_usersettings_daily_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordsprogress',
            name='was_learnt_once',
            field=models.BooleanField(default=False),
        ),
    ]
