# Generated by Django 5.2.3 on 2025-08-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_userwordsprogress_was_learnt_once'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Налаштування користувача', 'verbose_name_plural': 'Налаштування користувача'},
        ),
    ]
